[package]
name = "qkd"
version = "0.0.3"
edition = "2021"
authors = ["Daniel Escanez-Exposito <jescanez@ull.edu.es>"]
description = "A Quantum Key Distribution library developed in Rust"
license = "MIT"
repository = "https://github.com/jdanielescanez/qkd"
documentation = "https://docs.rs/qkd"

[dependencies]
bon = "3.7.2"
num-complex = "0.4.6"
rand = "0.9.2"
statrs = "0.18.0"

[lib]
name = "qkd"
path = "src/lib.rs"
